language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yoavxyoav/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true yoavxyoav/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-397468405767"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY